# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sercha < Formula
  desc "Local-first semantic search engine"
  homepage "https://github.com/custodia-labs/sercha-cli"
  version "0.2.3"
  license "Apache-2.0"

  depends_on "poppler" => :required
  depends_on "xapian" => :required

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/custodia-labs/sercha-cli/releases/download/v0.2.3/sercha_0.2.3_darwin_arm64.tar.gz"
      sha256 "f3c9c2f1ceafccd39a88b2ab3e6ce9ed1a4219dcf90953ea257735bcbd164788"

      def install
        bin.install "sercha"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/custodia-labs/sercha-cli/releases/download/v0.2.3/sercha_0.2.3_linux_amd64.tar.gz"
      sha256 "5352044b57dbbb4516c2505954d0a62a8cc28ebbdc077c1f1d85a53acdb3d995"
      def install
        bin.install "sercha"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/custodia-labs/sercha-cli/releases/download/v0.2.3/sercha_0.2.3_linux_arm64.tar.gz"
      sha256 "1f5a54750a1d5f083a90be3326a22cea09e9a4977f754169c9cbca301d36f685"
      def install
        bin.install "sercha"
      end
    end
  end
end
