# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sercha < Formula
  desc "Local-first semantic search engine"
  homepage "https://github.com/custodia-labs/sercha-cli"
  version "0.2.1"
  license "Apache-2.0"

  depends_on "poppler" => :required
  depends_on "xapian" => :required

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/custodia-labs/sercha-cli/releases/download/v0.2.1/sercha_0.2.1_darwin_arm64.tar.gz"
      sha256 "a7d5e0092763b433daa2a12962767d37590f31656656fcfa31b8257e4b6cba0a"

      def install
        bin.install "sercha"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/custodia-labs/sercha-cli/releases/download/v0.2.1/sercha_0.2.1_linux_amd64.tar.gz"
      sha256 "e835d8ec28c812a5b69759263a5fdbcd274a3c4ac508e40a14ceb39f17f3fd13"
      def install
        bin.install "sercha"
      end
    end
  end
end
