# This file was generated by GoReleaser. DO NOT EDIT.
cask "sercha" do
  name "sercha"
  desc "Sercha CLI"
  homepage "https://github.com/custodia-labs/sercha-cli"
  version "0.1.1b"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sercha"

  on_macos do
    on_intel do
      url "https://github.com/custodia-labs/sercha-cli/releases/download/v#{version}/sercha_#{version}_darwin_amd64.tar.gz"
      sha256 "a7e76b83703656f736cc1273bdb21a821d2829f7445fdb563b02cbf2d3fded83"
    end
    on_arm do
      url "https://github.com/custodia-labs/sercha-cli/releases/download/v#{version}/sercha_#{version}_darwin_arm64.tar.gz"
      sha256 "f65c1fca54ddae1ab2a8a00da4716b9ec311af150757b00f036abf372e3b13c3"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/custodia-labs/sercha-cli/releases/download/v#{version}/sercha_#{version}_linux_amd64.tar.gz"
      sha256 "b49977f4bd01e264040ed5e082e10b0c02e4440423d4e2cf73659b9a9b3ecb08"
    end
    on_arm do
      url "https://github.com/custodia-labs/sercha-cli/releases/download/v#{version}/sercha_#{version}_linux_arm64.tar.gz"
      sha256 "2c599a2c3676118150ba1148837ee31b9d424f40688cdeac48a75fe4c075f82f"
    end
  end

  # No zap stanza required
end
