# This file was generated by GoReleaser. DO NOT EDIT.
cask "sercha" do
  name "sercha"
  desc "Sercha CLI"
  homepage "https://github.com/custodia-labs/sercha-cli"
  version "0.1.1a"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sercha"

  on_macos do
    on_intel do
      url "https://github.com/custodia-labs/sercha-cli/releases/download/v#{version}/sercha_#{version}_darwin_amd64.tar.gz"
      sha256 "2b53d95a4fe4678ab8c2dbea3bcfa1413d46c2455ec151a14c660b267127816a"
    end
    on_arm do
      url "https://github.com/custodia-labs/sercha-cli/releases/download/v#{version}/sercha_#{version}_darwin_arm64.tar.gz"
      sha256 "92ede323a2de4112dab1661aa306064aef385a2375702ba279b3207ee7eceae2"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/custodia-labs/sercha-cli/releases/download/v#{version}/sercha_#{version}_linux_amd64.tar.gz"
      sha256 "9ebe8a0b4c08268aa95dcbfd9b3ec16cf294614351014f526c5cae9dc35ef523"
    end
    on_arm do
      url "https://github.com/custodia-labs/sercha-cli/releases/download/v#{version}/sercha_#{version}_linux_arm64.tar.gz"
      sha256 "fad7504fc216a486e9309cc2d57d9f7527e55be59fa71d0fbae504d6af8a8309"
    end
  end

  # No zap stanza required
end
