# This file was generated by GoReleaser. DO NOT EDIT.
cask "sercha" do
  name "sercha"
  desc "Sercha CLI"
  homepage "https://github.com/custodia-labs/sercha-cli"
  version "0.1.1a"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sercha"

  on_macos do
    on_intel do
      url "https://github.com/custodia-labs/sercha-cli/releases/download/v#{version}/sercha_#{version}_darwin_amd64.tar.gz"
      sha256 "9310dd26200d34097705e25f1cf0f1cb980f41af755a49079f9ff4bfaef36c30"
    end
    on_arm do
      url "https://github.com/custodia-labs/sercha-cli/releases/download/v#{version}/sercha_#{version}_darwin_arm64.tar.gz"
      sha256 "52cffedf9a5f077f82861c2ad4ea03b70beb2fa2ebc86502e0c00f1f1525d920"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/custodia-labs/sercha-cli/releases/download/v#{version}/sercha_#{version}_linux_amd64.tar.gz"
      sha256 "1ae7c82c553128cc1c42f3687a1e0a8d53b8a4d0f65d6729afee0d88cf8ff2ef"
    end
    on_arm do
      url "https://github.com/custodia-labs/sercha-cli/releases/download/v#{version}/sercha_#{version}_linux_arm64.tar.gz"
      sha256 "2612cd99a752281e9617de0d7ff6df661b90c2d5debfd5c759a83d5fe901d2ee"
    end
  end

  # No zap stanza required
end
